http:
  routers:
    otp-service:
      rule: "Host(`otp-service.kythuat.vn`)"
      service: "otp-service"
      entrypoints:
        - websecure
      tls:
        certResolver: internal
      middlewares:
        - default-headers
        - rate-limit
        - secure-headers

  services:
    otp-service:
      loadBalancer:
        servers:
          - url: "http://otp-service:8080"
        healthCheck:
          path: "/health"
          interval: "30s"

  middlewares:
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    rate-limit:
      rateLimit:
        burst: 100
        average: 50

    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowOriginList:
          - https://web.kythuat.vn
          - https://otp-service.kythuat.vn
          - https://web-api.kythuat.vn
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"