http:
  routers:
    frontend:
      rule: "Host(`web.kythuat.vn`)"
      service: "frontend"
      entrypoints:
        - websecure
      tls:
        certResolver: internal
      middlewares:
        - lets-go-headers
        # - rate-limit
        # - secure-headers

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:4200"
        healthCheck:
          path: "/health"
          interval: "30s"

  middlewares:
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    rate-limit:
      rateLimit:
        burst: 100
        average: 50

    lets-go-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Connection: "keep-alive"
          Access-Control-Allow-Origin: "*"
          Access-Control-Allow-Methods: "GET, PUT, POST, DELETE, OPTIONS"
          Access-Control-Allow-Headers: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    # secure-headers:
    #   headers:
    #     accessControlAllowMethods:
    #       - GET
    #       - OPTIONS
    #       - PUT
    #     accessControlAllowOriginList:
    #       - https://web.kythuat.vn
    #       - https://otp-service.kythuat.vn
    #       - https://localhost:1609
    #     accessControlMaxAge: 100
    #     hostsProxyHeaders:
    #       - "X-Forwarded-Host"
