services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: webbanhang
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: mysql

  backend:
    build:
      context: ./App/backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/webbanhang?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    volumes:
      - ./App/backend:/app
      - maven-repo:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "1609:1609"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./App/angular:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  db_data:
  maven-repo:
