package com.project.webbanhang.configurations;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import lombok.Data;

@Configuration
@ConfigurationProperties(prefix = "app")
@Data
public class AppProperties {
    private String databaseUrl;
    private String databaseUsername;
    private String databasePassword;
    private String jwtSecret;
    private long jwtExpiration;
    
    // Getters and setters are automatically generated by Lombok @Data
}
