global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kythuat-monitor'

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Backend application metrics (nếu có Spring Boot Actuator)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:1609']
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    scrape_timeout: 10s

  # OTP Service metrics
  - job_name: 'otp-service'
    static_configs:
      - targets: ['otp-service:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis metrics (với redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s