spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  application:
    name: webbanhang
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT}

api:
  prefix: ${API_PREFIX}
jwt:
  expiration: ${JWT_EXPIRATION}
  secretKey: ${JWT_SECRET}
  #30 days = 30 * 24 * 60 * 60w
momo:
  endpoint: ${MOMO_ENDPOINT}
  partnerCode: ${MOMO_PARTNER_CODE}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}
  redirectUrl: ${MOMO_REDIRECT_URL}
  ipnUrl: ${MOMO_IPN_URL}
  requestType: ${MOMO_REQUEST_TYPE}