spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        #        dialect: ${SPRING_JPA_HIBERNATE_PROPERTIES_DIALECT:org.hibernate.dialect.SQLServerDialect}
        format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  application:
    name: webbanhang
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

server:
  port: ${SERVER_PORT}

#debug: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

api:
  prefix: ${API_PREFIX}
jwt:
  expiration: ${JWT_EXPIRATION}
  secretKey: ${JWT_SECRET}
  #30 days = 30 * 24 * 60 * 60w
momo:
  endpoint: ${MOMO_ENDPOINT}
  partnerCode: ${MOMO_PARTNER_CODE}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}
  redirectUrl: ${MOMO_REDIRECT_URL}
  ipnUrl: ${MOMO_IPN_URL}
  requestType: ${MOMO_REQUEST_TYPE}

goong:
  endpoint: ${GOONG_ENDPOINT:https://rsapi.goong.io}
  apiKey: ${GOONG_API_KEY}
