# TOP 10 OWASP 2023
# API8:2023 - Security Misconfiguration
# Hacker có thể khai thác các cấu hình mặc định không an toàn,
# cấu hình sai hoặc cấu hình lỏng lẻo trong ứng dụng,
# framework, máy chủ web, máy chủ ứng dụng, cơ sở dữ liệu và nền tảng.
#
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  application:
    name: webbanhang
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: REDIS
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

api:
  prefix: ${API_PREFIX}
jwt:
  expiration: ${JWT_EXPIRATION}
  secretKey: ${JWT_SECRET}
  #30 days = 30 * 24 * 60 * 60w
momo:
  endpoint: ${MOMO_ENDPOINT}
  partnerCode: ${MOMO_PARTNER_CODE}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}
  redirectUrl: ${MOMO_REDIRECT_URL}
  ipnUrl: ${MOMO_IPN_URL}
  requestType: ${MOMO_REQUEST_TYPE}

goong:
  endpoint: ${GOONG_ENDPOINT}
  apiKey: ${GOONG_API_KEY}
