spring:
  datasource:
    url: jdbc:mysql://db:3306/webbanhang?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  application:
    name: webbanhang
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 1609

api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: euv8p8iSXxKqR6MFGpOkUHd0UZDQFssKjB6JXM8OPVo
  #30 days = 30 * 24 * 60 * 60w