name: Deploy to Production

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./App/backEnd
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webbanhang-backend:${{ github.event.release.tag_name || 'latest' }}
        
    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./App/angular
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webbanhang-frontend:${{ github.event.release.tag_name || 'latest' }}
        
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd /path/to/deployment
          docker-compose pull
          docker-compose up -d
