name: Feature Branch Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
    paths:
      - 'App/backEnd/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
    paths:
      - 'App/backEnd/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: |
        cd App/backEnd
        mvn clean compile
        
    - name: Run Unit Tests
      run: |
        cd App/backEnd
        mvn test
        
    - name: Generate Test Report
      if: success() || failure()
      run: |
        cd App/backEnd
        mvn surefire-report:report
        
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: App/backEnd/target/surefire-reports
        
    - name: Comment Test Results
      if: github.event_name == 'pull_request'
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: App/backEnd/target/surefire-reports/*.xml