name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'App/angular/**'
      - '.github/workflows/frontend-ci-cd.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'App/angular/**'

permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # ...existing steps...
    
    - name: Run tests
      run: |
        cd App/angular
        npm test -- --watch=false --browsers=ChromeHeadless